### ISSUE TITLE
Behind a proxy, can't get authentication to work

### ISSUE THREAD

**Issue by skysgh** [davidfowl/NuGetPowerTools#14]
To not forget anything, I'm posting a link to the original post:

http://stackoverflow.com/questions/8175524/nuget-nugetpowertools-enable-packagerestore-authentication-failure-behind

**Comment by davidfowl** [comment]
This is really an issue with NuGet.exe, please file a bug on nuget.codeplex.com

**Comment by skysgh** [comment]
Hi David, 
Thanks for that response: I've forwarded  the question on to them:

http://bit.ly/uW6ghG

PS: Thanks for putting together the pack btw...much appreciated. Works like a charm...at home.
