### ISSUE TITLE
Enable-PackageRestore poisons projects for use in other solutions

### ISSUE THREAD

**Issue by DavidBoike** [davidfowl/NuGetPowerTools#19]
If you have a repository with one primary solution, and other secondary solutions in subfolders, using Enable-PackageRestore on the primary solution causes the shared projects to be unloadable in the subfolder solutions.

Example:

<pre>
- nuget\
- PrimarySolution.sln
- Components
    - Components.csproj
- Utilities
    - UtilitySolution.sln
</pre>

PrimarySolution and UtilitySolution both reference Components.csproj. So after enabling PackageRestore on PrimarySolution, UtilitySolution can't load Components.csproj. It says:

> One or more projects in the solution were not loaded correctly. Please see the Output Window for details.

Trying to reload the unloaded Components.csproj results in:

> Unable to read the project file 'Components.csproj' {Path to csproj file}: The imported project "{PathToRepositoryRoot}\Utilities.nuget\nuget.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Essentially, there is a difference between the Solution Directory and the Repository Root Directory in this case.  Not sure if there's a way within the Visual Studio paradigm for this to be addressed, but I don't have the PowerShell skills necessary to check it out myself.

**Comment by davidfowl** [comment]
2 things.
1. This is now a feature of nuget itself. (I need to deprecate Enable-PackageRestore)
2. There's no powershell involved here (it's all msbuild) and we need to use some solution root (since that's where nuget puts the .nuget folder). NuGet itself doesn't even work well with solutions in different parts of your repo since the we base the packages folder off the solution root as well.

**Comment by DavidBoike** [comment]
Ah, I knew the functionality had been baked into NuGet 1.6, but I thought the source code was still coming from here!

I figured there may not be a way to get around the problem besides relocating solutions to the repository root. I guess now I know that's definitely the best course of action.  Thanks!

**Comment by brgrz** [comment]
This is actually extremelly annoying error. Once you enable package restore in a solution with multiple projects and then try to Add these to projects to another solutions, this error will be displayed and you can't do anything about it. All projects are poisened then. Also, how does one disable package restore for a solution?

**Comment by brgrz** [comment]
Removing this line manually in each affected .csproj file solves the issue but this is just lame..

Import Project="$(SolutionDir).nuget\nuget.targets"

Once you enable package restore you can't even open the project as a standalone project anymore..so this just another Nuget halfway done thing...

**Comment by davidfowl** [comment]
That's by design. The only alternative that would make it work would be a custom task that finds the nuget.targets dynamically based on the project path but that's something we might add to .nuget itself.

**Comment by woodyb23** [comment]
This page saved my ass as I was having serious issues trying to figure out how to fix this after using Nuget Package Restore. Now  my issue is that my tests no longer run because it cannot find the namespace to my current project. Anyone know how to fix this part?

**Comment by knocte** [comment]
@davidfowl , so then if Enable-PackageRestore is deprecated, what's the OneTrueWay now? Any URL to the doc?

**Comment by davidfowl** [comment]
http://docs.nuget.org/docs/workflows/using-nuget-without-committing-packages

**Comment by martys** [comment]
Having the same issue, while trying to reuse the project in another solution. Package restore is a wonderful feature and I'd like to keep it, and be able to only update the  :
      "Import Project="$(SolutionDir).nuget\nuget.targets" "
to 
      "Import Project="...nuget\nuget.targets" "

That would solve all my issues :)

**Comment by brgrz** [comment]
lol issue closed and the problem still present with brand new VS2012 and latest Nuget install..this is so stupid issue that it hurts. DuctTapeMan correctly named it "poisons" because that's what it does. Nuget Package Restore is broken I don't get it how no one sees that...~~~

**Comment by davidfowl** [comment]
File a bug on nuget

**Comment by kingdango** [comment]
Still occurring.  Thank God for this page.

**Comment by davidfowl** [comment]
This project has been dead forever. Package restore is now built into nuget and you shouldn't be using this package anymore.
