### ISSUE TITLE
PackagesDir should take into account nuget.config

### ISSUE THREAD

**Issue by NikGovorov** [davidfowl/NuGetPowerTools#2]
Hello, David.

I always have nuget.config in my solution folder:

``` xml
<settings>
<repositoryPath>..\Packages</repositoryPath>
</settings>
```

So it would be great if the powertools would take into account 'repositoryPath' from this file.

**Comment by davidfowl** [comment]
That's an unsupported feature, and I'm not sure I want to support it. But to work around it, you can tweak the targets file (NuGet.settings.targets) to point to your folder (I know it's not DRY :))

**Comment by NikGovorov** [comment]
Do you mean nuget team can drop this feature in the next releases?

**Comment by davidfowl** [comment]
Yep, we're going to make the feature more official, but most likely the syntax of the nuget.config file will change to be more lik the NuGet.config in %AppData%\NuGet.config

**Comment by NikGovorov** [comment]
I hope it will still save feature of the setting custom location of the packages folder.
Cheers.
