### ISSUE TITLE
Support for VS 2012 appears to be lacking

### ISSUE THREAD

**Issue by rpedersen** [davidfowl/NuGetPowerTools#23]
After added the package and going to the Package Manager Console I ran: Enable-PackageBuild

The following errors were reported...

Failed to add import 'NuGet.targets' to <Project Name>

The error message was repeated 3 times, once for each of the 3 projects in the solution. The projects

**Comment by davidfowl** [comment]
This package is deprecated. I'll updated it since the functionality is built into NuGet itself.
