### ISSUE TITLE
Make NuGetPowerTools more independant of the NuGet's version

### ISSUE THREAD

**Issue by mgrosperrin** [davidfowl/NuGetPowerTools#3]
Hi,

I'm trying your very interresting way to enable the usage of NuGet without committing packages to source control and I have a little request to improve (a little) it :
You should include in the NuGet.Build package the bootstrapper of NuGet (instead of the current version of NuGet) and run it before every targets (may be in the CheckPrerequisites target) to tell him to auto update to the last version. With this little improvement, we won't have to manually update the NuGet.exe file in the source control to have the last version.

Thanks.

**Comment by dennismi** [comment]
I second this, we could always just replace the checked in version with the bootstrapper :) 

but bootstrapper on initial install would be a plus

**Comment by mgrosperrin** [comment]
We could replace the checked in version with the bootstrapper, but we must insure that the bootstrapper have been run before every call of NuGet. So the tasks must  be updated to handle it.

**Comment by dennismi** [comment]
you got a point there, but the feature is still nice :)

**Comment by mgrosperrin** [comment]
Yes, and I am planning to use it as is for now !

**Comment by davidfowl** [comment]
I don't like this. That'll slow things down. If you want, you can modify the targets file to suit your needs.
