### ISSUE TITLE
Merging enabled projects

### ISSUE THREAD

**Issue by dennismi** [davidfowl/NuGetPowerTools#7]
Hi again, David

I've experiencing some issues with your tools when merging my code from branch to branch... 
ie. I've got it set up at a release branch, then i merged it back into our main branch, but then our build server couldn't find the libraries, but all options were intact in the project file ... after running install nugetpowertools and enable-packagerestore every works just dandy again ... 

I haven't checked in the powertools package... just the files in the .nuget folder :)

I don't suspect that this is the intended behaviour, It's not a big deal YET. Don't know if this will be obsoleted by v 1.6?

regards
dennis

**Comment by davidfowl** [comment]
1. What errors did you get?
2. Yes this package will be obsolete :) and functionality will be baked in.
