### ISSUE TITLE
Running locally (no web connection)

### ISSUE THREAD

**Issue by kshahar** [davidfowl/NuGetPowerTools#9]
Hi David,

Thanks for sharing this code :)

I'm running NuGet in an environment without a web connection. All packages are kept on a shared directory (NuGet "local reopsitory").

Without a web connection, there is a problem with the NuGetMSBuild.psm1 file and this line:

```
Install-Package NuGet.Build -Source 'https://go.microsoft.com/fwlink/?LinkID=206669'
```

Is the "Source" option really needed here?
I copied NuGet.Build and the dependencies to the local repository, removed the "Source" option and it worked fine.

Thanks,
Shahar

**Comment by davidfowl** [comment]
I don't want to rely on your configured sources.
